spring:
  application:
    name: beacon

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/beacon}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${EMAIL_SERVER_HOST}
    port: ${EMAIL_SERVER_PORT}
    username: ${EMAIL_SERVER_USERNAME}
    password: ${EMAIL_SERVER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

  sms:
    provider: ${SMS_PROVIDER:twilio} # could also be aws
    twilio:
      base-url: ${SMS_TWILIO_BASE_URL:https://api.twilio.com/2010-04-01}
      account-sid: ${SMS_TWILIO_ACCOUNT_SID:}
      auth-token: ${SMS_TWILIO_AUTH_TOKEN:}
      from-number: ${SMS_TWILIO_FROM_NUMBER:}
    aws:
      access-key: ${SMS_AWS_ACCESS_KEY:}
      secret-key: ${SMS_AWS_SECRET_KEY:}
      region: ${SMS_AWS_REGION:us-east-1}

  push:
    provider: ${PUSH_PROVIDER:firebase} # could also be aws or onesignal
    firebase:
      credentials-path: ${PUSH_FIREBASE_CREDENTIALS_PATH:}
    aws:
      platform-application-arn: ${PUSH_AWS_PLATFORM_APPLICATION_ARN:}
    onesignal:
      base-url: ${PUSH_ONESIGNAL_BASE_URL:https://api.onesignal.com}
      app-id: ${PUSH_ONESIGNAL_APP_ID:}
      api-key: ${PUSH_ONESIGNAL_API_KEY:}